id: IE5E4C848
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:55:47+00:00'
last_modified: '2022-06-07T14:51:44.267098+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22166
  title: ཐེག་པ་སྤྱི་བཅིངས་རྩ་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9F4C:
      image_group_id: I4226
      title: ''
      total_pages: 482
      order: 1
      base_file: 9F4C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
